server:
  port: 8585
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v3/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v3/**
        - id: dish-service
          uri: lb://dish-service
          predicates:
            - Path=/api/v3/**
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/v3/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
