server:
  port: 8585
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-service-bookroom
          uri: lb://booking-service
          predicates:
            - Path=/api/v3/bookroom

        - id: booking-service-updatebooking
          uri: lb://booking-service
          predicates:
            - Path=/api/v3/updatebooking/{id}

        - id: booking-service-mybookings
          uri: lb://booking-service
          predicates:
            - Path=/api/v3/mybookings

        - id: dish-service-sushis
          uri: lb://dish-service
          predicates:
            - Path=/api/v3/sushis

        - id: dish-service-sushis-id
          uri: lb://dish-service
          predicates:
            - Path=/api/v3/sushis/{id}

        - id: dish-service-add-dish
          uri: lb://dish-service
          predicates:
            - Path=/api/v3/add-dish

        - id: dish-service-deletedish
          uri: lb://dish-service
          predicates:
            - Path=/api/v3/deletedish/{id}

        - id: customer-service-customers
          uri: lb://customer-service
          predicates:
            - Path=/api/v3/customers

        - id: room-service-updateroom
          uri: lb://room-service
          predicates:
            - Path=/api/v3/updateroom/{id}

        - id: room-service-getroom
          uri: lb://room-service
          predicates:
            - Path=/api/v3/rooms/{id}

        - id: currency-service-sektoeuro
          uri: lb://currency-service
          predicates:
            - Path=/api/v3/sektoeuro
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
