server:
  port: 8585
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: sushi-service
          uri: lb://sushi-service
          predicates:
            - Path=/api/v3/**

        - id: WIGELL-TRAVELS
          uri: lb://WIGELL-TRAVELS
          predicates:
            - Path=/api/v2/**

        - id: currency-service-sektoeuro
          uri: lb://currency-service
          predicates:
            - Path=/api/v3/sektoeuro
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
